import type { RawFixture } from '@/lib/types';
import {
  cloneJson,
  deleteAtPath,
  flatten,
  getAtPath,
  type LedgerRow,
  type LedgerSection,
} from '@/lib/data-ledger';

export type { LedgerRow, LedgerSection };

/**
 * Hand-picked translations for the API-Sports field names that are worth
 * reading cleanly (e.g. `short` → "Status Code" rather than just "Short").
 * This is a literal name → label dictionary, not narrative copy — anything
 * NOT listed here still renders, just under a label generated by humanizing
 * its own path. That's what keeps this "data-first": no field is ever hidden
 * for lacking a curated translation.
 */
const LABEL_OVERRIDES: Record<string, string> = {
  'fixture.id': 'Fixture ID',
  'fixture.referee': 'Referee',
  'fixture.date': 'Kickoff',
  'fixture.timezone': 'Timezone',
  'fixture.status.long': 'Status',
  'fixture.status.short': 'Status Code',
  'fixture.status.elapsed': 'Minutes Elapsed',
  'fixture.venue.name': 'Venue',
  'fixture.venue.city': 'City',
  'league.id': 'League ID',
  'league.name': 'Competition',
  'league.country': 'Country',
  'league.logo': 'League Crest',
  'league.flag': 'Country Flag',
  'league.season': 'Season',
  'league.round': 'Round',
  'teams.home.id': 'Home Team ID',
  'teams.home.name': 'Home Team',
  'teams.home.logo': 'Home Team Crest',
  'teams.home.winner': 'Home Team Won',
  'teams.away.id': 'Away Team ID',
  'teams.away.name': 'Away Team',
  'teams.away.logo': 'Away Team Crest',
  'teams.away.winner': 'Away Team Won',
  goals: 'Score',
  'score.halftime': 'Half-time Score',
  'score.fulltime': 'Full-time Score',
  'score.extratime': 'Extra-time Score',
  'score.penalty': 'Penalty Shoot-out',
};

/**
 * Logical groupings the user asked for ("Match Status", "Teams & Scores",
 * "Officials & Venue"), expressed as paths INTO the raw fixture object.
 * Every path is consumed (and removed from the working copy) in order —
 * whatever the API returns at that path is flattened into rows automatically,
 * and whatever's missing simply contributes nothing. Anything left over after
 * every defined section has claimed its paths still surfaces, in "Additional
 * Data" below — so the ledger always covers the ENTIRE fixture object, not
 * just the fields we anticipated.
 */
const SECTION_DEFS: { title: string; paths: string[] }[] = [
  { title: 'Match Status', paths: ['fixture.status', 'fixture.date', 'fixture.timezone', 'fixture.id'] },
  { title: 'Teams & Scores', paths: ['teams', 'goals', 'score'] },
  { title: 'Officials & Venue', paths: ['fixture.referee', 'fixture.venue'] },
  { title: 'Competition', paths: ['league'] },
];

/**
 * The data-mapping function behind `MatchHeader`: turns one raw API-Sports
 * fixture object into a grouped, render-ready ledger (id, score, status, plus
 * everything else the payload carries). Defined sections claim the well-known
 * parts of the schema first — and are dropped entirely if the API omitted
 * them (e.g. no `score` block pre-kickoff means no score rows, never blank
 * ones). A final generic pass over whatever's left guarantees full coverage,
 * including fields this mapping wasn't written to expect.
 */
export function buildFixtureLedger(raw: RawFixture): LedgerSection[] {
  const working = cloneJson(raw) as unknown as Record<string, unknown>;
  const sections: LedgerSection[] = [];

  for (const def of SECTION_DEFS) {
    const rows: LedgerRow[] = [];
    for (const path of def.paths) {
      const segments = path.split('.');
      const value = getAtPath(working, segments);
      if (value === undefined) continue;
      rows.push(...flatten(value, segments, LABEL_OVERRIDES));
      deleteAtPath(working, segments);
    }
    if (rows.length > 0) sections.push({ title: def.title, rows });
  }

  const remainder = flatten(working, [], LABEL_OVERRIDES);
  if (remainder.length > 0) sections.push({ title: 'Additional Data', rows: remainder });

  return sections;
}
